{{- if .Values.sortinghat.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grimoirelab.fullname" . }}-sortinghat
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "grimoirelab.labels" . | nindent 4 }}
    app.kubernetes.io/component: sortinghat
spec:
  replicas: {{ .Values.sortinghat.replicas }}
  selector:
    matchLabels:
      {{- include "grimoirelab.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: sortinghat
  template:
    metadata:
      labels:
        {{- include "grimoirelab.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: sortinghat
    spec:
      serviceAccountName: {{ include "grimoirelab.serviceAccountName" . }}
      initContainers:
        {{- include "grimoirelab.waitForService" (dict "service" "mariadb" "host" (include "grimoirelab.mariadb.host" .) "port" .Values.mariadb.service.port) | nindent 8 }}
      containers:
        - name: sortinghat
          image: {{ include "grimoirelab.image" (dict "global" .Values.global "repository" .Values.sortinghat.image.repository "tag" .Values.sortinghat.image.tag) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "grimoirelab.fullname" . }}-config
                  key: log-level
            - name: SORTINGHAT_AUTO_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "grimoirelab.fullname" . }}-sortinghat-config
                  key: auto-profile
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "grimoirelab.fullname" . }}-config
                  key: mariadb-host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "grimoirelab.fullname" . }}-config
                  key: mariadb-port
            - name: DATABASE_NAME
              valueFrom:
                secretRef:
                  name: {{ include "grimoirelab.fullname" . }}-sortinghat-dbcreds
                  key: database
            - name: DATABASE_USER
              valueFrom:
                secretRef:
                  name: {{ include "grimoirelab.fullname" . }}-sortinghat-dbcreds
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretRef:
                  name: {{ include "grimoirelab.fullname" . }}-sortinghat-dbcreds
                  key: password
            - name: SECRET_KEY
              valueFrom:
                secretRef:
                  name: {{ include "grimoirelab.fullname" . }}-sortinghat-secrets
                  key: secret-key
          resources:
            {{- toYaml .Values.sortinghat.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
{{- end }}
