{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grimoirelab.fullname" . }}-mariadb-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "grimoirelab.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
type: Opaque
data:
  root-password: {{ .Values.mariadb.auth.rootPassword | b64enc }}
  username: {{ .Values.mariadb.auth.username | b64enc }}
  password: {{ .Values.mariadb.auth.password | b64enc }}
---
# Separate secrets for each service that needs database access
{{- if .Values.arthur.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grimoirelab.fullname" . }}-arthur-dbcreds
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "grimoirelab.labels" . | nindent 4 }}
    app.kubernetes.io/component: arthur
type: Opaque
data:
  username: {{ .Values.arthur.secrets.dbUser | b64enc }}
  password: {{ .Values.arthur.secrets.dbPassword | b64enc }}
  database: {{ .Values.mariadb.auth.database | b64enc }}
---
{{- end }}
{{- if .Values.graal.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grimoirelab.fullname" . }}-graal-dbcreds
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "grimoirelab.labels" . | nindent 4 }}
    app.kubernetes.io/component: graal
type: Opaque
data:
  username: {{ .Values.graal.secrets.dbUser | b64enc }}
  password: {{ .Values.graal.secrets.dbPassword | b64enc }}
  database: {{ .Values.mariadb.auth.database | b64enc }}
---
{{- end }}
{{- if .Values.sortinghat.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grimoirelab.fullname" . }}-sortinghat-dbcreds
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "grimoirelab.labels" . | nindent 4 }}
    app.kubernetes.io/component: sortinghat
type: Opaque
data:
  username: {{ .Values.sortinghat.secrets.dbUser | b64enc }}
  password: {{ .Values.sortinghat.secrets.dbPassword | b64enc }}
  database: {{ .Values.mariadb.auth.database | b64enc }}
---
{{- end }}
{{- end }}
