{{- if .Values.perceval.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grimoirelab.fullname" . }}-perceval
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "grimoirelab.labels" . | nindent 4 }}
    app.kubernetes.io/component: perceval
spec:
  replicas: {{ .Values.perceval.replicas }}
  selector:
    matchLabels:
      {{- include "grimoirelab.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: perceval
  template:
    metadata:
      labels:
        {{- include "grimoirelab.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: perceval
    spec:
      serviceAccountName: {{ include "grimoirelab.serviceAccountName" . }}
      initContainers:
        {{- include "grimoirelab.waitForService" (dict "service" "elasticsearch" "host" (include "grimoirelab.elasticsearch.host" .) "port" .Values.elasticsearch.service.port) | nindent 8 }}
      containers:
        - name: perceval
          image: {{ include "grimoirelab.image" (dict "global" .Values.global "repository" .Values.perceval.image.repository "tag" .Values.perceval.image.tag) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "grimoirelab.fullname" . }}-config
                  key: log-level
            - name: ELASTICSEARCH_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "grimoirelab.fullname" . }}-config
                  key: elasticsearch-url
            - name: PERCEVAL_BACKENDS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "grimoirelab.fullname" . }}-perceval-config
                  key: backends
            - name: GITHUB_TOKEN
              valueFrom:
                secretRef:
                  name: {{ include "grimoirelab.fullname" . }}-perceval-secrets
                  key: github-token
                  optional: true
            - name: JIRA_USERNAME
              valueFrom:
                secretRef:
                  name: {{ include "grimoirelab.fullname" . }}-perceval-secrets
                  key: jira-username  
                  optional: true
            - name: JIRA_PASSWORD
              valueFrom:
                secretRef:
                  name: {{ include "grimoirelab.fullname" . }}-perceval-secrets
                  key: jira-password
                  optional: true
          command:
            - python3
            - -m
            - perceval
            - --help
          resources:
            {{- toYaml .Values.perceval.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
{{- end }}
