{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "grimoirelab.fullname" . }}-netpol
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "grimoirelab.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "grimoirelab.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow ingress from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 5601  # Kibiter
        - protocol: TCP
          port: 8080  # Arthur
        - protocol: TCP
          port: 5000  # Sigils
    # Allow inter-service communication
    - from:
        - podSelector:
            matchLabels:
              {{- include "grimoirelab.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 9200  # Elasticsearch
        - protocol: TCP
          port: 3306  # MariaDB
        - protocol: TCP
          port: 6379  # Redis
        - protocol: TCP
          port: 8000  # Perceval
        - protocol: TCP
          port: 8080  # Arthur
        - protocol: TCP
          port: 8081  # Graal
        - protocol: TCP
          port: 8082  # SortingHat
        - protocol: TCP
          port: 5000  # Sigils
        - protocol: TCP
          port: 5601  # Kibiter
    {{- with .Values.networkPolicy.ingress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
    # Allow inter-service communication
    - to:
        - podSelector:
            matchLabels:
              {{- include "grimoirelab.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 9200  # Elasticsearch
        - protocol: TCP
          port: 3306  # MariaDB
        - protocol: TCP
          port: 6379  # Redis
        - protocol: TCP
          port: 8000  # Perceval
        - protocol: TCP
          port: 8080  # Arthur
        - protocol: TCP
          port: 8081  # Graal
        - protocol: TCP
          port: 8082  # SortingHat
        - protocol: TCP
          port: 5000  # Sigils
        - protocol: TCP
          port: 5601  # Kibiter
    # Allow external API access (for data collection)
    - to: []
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
