apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grimoirelab.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "grimoirelab.labels" . | nindent 4 }}
type: Opaque
data:
  # MariaDB root credentials
  mariadb-root-password: {{ .Values.mariadb.auth.rootPassword | b64enc }}
  mariadb-user: {{ .Values.mariadb.auth.username | b64enc }}
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc }}
  
  # Redis credentials
  redis-password: {{ .Values.redis.auth.password | b64enc }}
  
  # GitHub token for Perceval
  github-token: {{ .Values.perceval.secrets.githubToken | default "" | b64enc }}
  
  # JIRA credentials for Perceval
  jira-username: {{ .Values.perceval.secrets.jiraUsername | default "" | b64enc }}
  jira-password: {{ .Values.perceval.secrets.jiraPassword | default "" | b64enc }}
  
  # SortingHat secret key
  sortinghat-secret-key: {{ .Values.sortinghat.secrets.secretKey | b64enc }}
